### ISSUE TITLE
Accessing data error

### ISSUE THREAD

**Issue by brownad** [JonathanH5/homebridge-myflowerpower#1]
Hi,

I signed up for the OAuth token, received the mail from Parrot with Access_code (my email) and Secret Access (token).  Is this simply passed in to client_id and client_secret?  Or am I missing something?  Also is location required?

**Comment by MoeweX** [comment]
Hi brownad,
The client took advantage of the fact that all data is uploaded to a web server hosted by parrot which could be queried (a lot easier to implement than communicating directly with the device). Unfortunately, it seems like parrot has stopped this web server so the code is not working anymore. If I a wrong about this tell me and I will look into this again, but I could not find it this morning anymore... .

**Comment by brownad** [comment]
Hi I think the api has changed a bit - the end point that you're hitting doesn't exist. Auth has changed on their side.  I assume you no longer receive updates?

**Comment by MoeweX** [comment]
Hi, they used to have a website to visualize the data and this one is down. It was called myflowerpower. Because this one is down I figured they deprecated the service, did not they?

**Comment by brownad** [comment]
In that case it's gone... but the api has moved on as per their docs. Auth and other things have changed somewhat

**Comment by brownad** [comment]
Is this not correct?

http://developer.parrot.com/docs/FlowerPower/

**Comment by brownad** [comment]
Did you ever have a chance to see if it could work again, it's a cool plugin would be great to use it as a sensor

**Comment by MoeweX** [comment]
Hi, from what I saw it does not work anymore. I would love to make it usable again, because I also use these sensors and homebridge... .

Von meinem iPhone gesendet

> Am 31.01.2017 um 22:14 schrieb brownad <notifications@github.com>:
> 
> Did you ever have a chance to see if it could work again, it's a cool plugin would be great to use it as a sensor 
> 
> Sent from my iPhone
>

**Comment by brownad** [comment]
There's a nice nose module to help with auth to make this work again

https://www.npmjs.com/package/node-flower-power

**Comment by brownad** [comment]
Meant node
